"""add_event_indexes

Revision ID: 4433dff94dae
Revises: 00b3555a5e95
Create Date: 2026-02-21 08:29:17.658585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4433dff94dae'
down_revision = '00b3555a5e95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_events_end_dt'), 'events', ['end_dt'], unique=False)
    op.create_index(op.f('ix_events_start_dt'), 'events', ['start_dt'], unique=False)
    op.create_index(op.f('ix_events_sub_calendar_id'), 'events', ['sub_calendar_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_sub_calendar_id'), table_name='events')
    op.drop_index(op.f('ix_events_start_dt'), table_name='events')
    op.drop_index(op.f('ix_events_end_dt'), table_name='events')
    # ### end Alembic commands ###
