"""add_creator_user_id_to_events

Revision ID: 4ca9cfa8c179
Revises: 3e44d1046d69
Create Date: 2026-02-20 17:19:04.149020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca9cfa8c179'
down_revision = '3e44d1046d69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('creator_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['creator_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'creator_user_id')
    # ### end Alembic commands ###
